### ISSUE TITLE
Importing OMGHTTPURLRQ via Carthage fails

### ISSUE THREAD

**Issue by olbrichj** [PromiseKit/OMGHTTPURLRQ#3]
Xcode 8.2.1 with Swift 3

Cartfile:
```
github "mxcl/PromiseKit"
github "PromiseKit/OMGHTTPURLRQ" ~> 1.0
```

Error:
```
*** Checking out OMGHTTPURLRQ at "1.0.0"
A shell task (/usr/bin/env git checkout --quiet --force 1.0.0) failed with exit code 1:
error: pathspec '1.0.0' did not match any file(s) known to git.
```

This is probably due to having the same checkout name as mxcl/OMGHTTPURLRQ and thus overriding the other project.

**Comment by mxcl** [comment]
Carthage bug. But we can work around it.

You should report the bug to Carthage too.

**Comment by mxcl** [comment]
Fixed by renaming `OMGHTTPURLRQ-`

Please report the bug to Carthage, they shouldn't rely on a single-namespace when their dependency resolution allows names with full URLs.

**Comment by olbrichj** [comment]
Thx will do :)
