### ISSUE TITLE
Unable to install through carthage

### ISSUE THREAD

**Issue by killergerbah** [PromiseKit/OMGHTTPURLRQ#5]
Using carthage update with the provided command yields the following error:
rlim$ carthage update
*** Fetching OMGHTTPURLRQ
*** Fetching PromiseKit
*** Fetching OMGHTTPURLRQ
*** Fetching Foundation
*** Checking out OMGHTTPURLRQ at "1.0.1"
A shell task (/usr/bin/env git checkout --quiet --force 1.0.1) failed with exit code 1:
error: pathspec '1.0.1' did not match any file(s) known to git.

My Cartfile looks like this:
rlim$ cat Cartfile
github "PromiseKit/OMGHTTPURLRQ" ~> 1.0

**Comment by mxcl** [comment]
Dupes #3

**Comment by mxcl** [comment]
Specify `github "PromiseKit/OMGHTTPURLRQ-"`.

**Comment by mxcl** [comment]
I updated the docs, sorry, this was my bad.
